# Generated by Django 4.1.2 on 2022-10-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('topic', models.CharField(max_length=50, verbose_name='topic')),
                ('message', models.CharField(max_length=50, verbose_name='topic')),
                ('up_votes', models.IntegerField(default=0, verbose_name='up')),
                ('down_votes', models.IntegerField(default=0, verbose_name='down')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
            ],
        ),
    ]
