# Generated by Django 4.1.2 on 2022-10-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_review_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='up_votes',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_votes', models.IntegerField(default=0, verbose_name='up')),
                ('down_votes', models.IntegerField(default=0, verbose_name='down')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.review', verbose_name='')),
            ],
        ),
    ]
